name: Publish to Modrinth

on:
  release:
    types: [ published ]

jobs:
  modrinth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - run: ./gradlew build

      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: RLrPqrNI
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
